/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package front;

import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.Client;
import process.BankProcess;


/**
 *
 * @author carlosforero
 */
public class InternalAccount extends javax.swing.JInternalFrame {
private HashMap<String,Client> clients_import;
    /**
     * Creates new form InternalAccount
     */
    public InternalAccount() {
        clients_import = process.BankProcess.get_Clients();
        initComponents();
        get_clients();
        refresh();
    }
    private void refresh(){
        cleanJtable();
        writeJtable();
    }
  
    
    private void cleanJtable(){
        DefaultTableModel model = (DefaultTableModel) jTableAccounts.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
    }
    private void writeJtable(){
        DefaultTableModel model = (DefaultTableModel) jTableAccounts.getModel();
        HashMap<String,Account> accounts = process.BankProcess.get_Accounts();
        for (Map.Entry<String, Account> entry : accounts.entrySet()) {
            model.addRow(new Object[]{entry.getValue().get_client().get_id(),entry.getValue().get_client().get_first_name(),entry.getValue().get_client().get_last_name(),entry.getValue().get_numberAccount(),entry.getValue().get_limit_per_amount(),entry.getValue().get_limit_per_day(),entry.getValue().get_overdraft()});
        }
        
        revalidate();
    }
    public void get_clients(){
        
        HashMap<String,Client> clientes = process.BankProcess.get_Clients();
        for (Map.Entry<String, Client> entry : clientes.entrySet()) {
            jComboBoxClient.addItem(entry.getValue().get_id());
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAddFirstName = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldAddLimit_per_day = new javax.swing.JTextField();
        jTextFieldAddLimit_per_amount = new javax.swing.JTextField();
        jLabelAddLastName = new javax.swing.JLabel();
        jLabelAddType = new javax.swing.JLabel();
        Identification = new javax.swing.JLabel();
        jComboBoxClient = new javax.swing.JComboBox<>();
        jTextFieldAddOverDraft = new javax.swing.JTextField();
        jLabelClientName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAccounts = new javax.swing.JTable();

        jLabelAddFirstName.setText("Limite por dia");

        jButtonAdd.setText("Registrar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelAddLastName.setText("Limite por retiro $");

        jLabelAddType.setText("Sobregiro");

        Identification.setText("Cliente");

        jComboBoxClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientActionPerformed(evt);
            }
        });

        jLabelClientName.setText("Client_name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddFirstName)
                    .addComponent(jLabelAddLastName)
                    .addComponent(jLabelAddType)
                    .addComponent(Identification))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxClient, 0, 268, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddLimit_per_amount)
                    .addComponent(jTextFieldAddLimit_per_day, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddOverDraft))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonAdd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelClientName)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Identification)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxClient, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelClientName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddFirstName)
                    .addComponent(jTextFieldAddLimit_per_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddLimit_per_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAddLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddType)
                    .addComponent(jButtonAdd)
                    .addComponent(jTextFieldAddOverDraft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTableAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificacion Cliente", "Primer Nombre", "Apellido", "Numero de Cuenta", "Limite por retiro", "Limite por dia", "Sobregiro"
            }
        ));
        jScrollPane1.setViewportView(jTableAccounts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try{
            BankProcess.Create_account(jComboBoxClient.getSelectedItem().toString(), Integer.parseInt(jTextFieldAddLimit_per_day.getText()),Integer.parseInt(jTextFieldAddLimit_per_amount.getText()), Integer.parseInt(jTextFieldAddOverDraft.getText())); 
        }
        catch(NumberFormatException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientActionPerformed
        jLabelClientName.setText(clients_import.get(jComboBoxClient.getSelectedItem().toString()).get_first_name()+ " "+clients_import.get(jComboBoxClient.getSelectedItem().toString()).get_last_name());
        refresh();
    }//GEN-LAST:event_jComboBoxClientActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Identification;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<String> jComboBoxClient;
    private javax.swing.JLabel jLabelAddFirstName;
    private javax.swing.JLabel jLabelAddLastName;
    private javax.swing.JLabel jLabelAddType;
    private javax.swing.JLabel jLabelClientName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAccounts;
    private javax.swing.JTextField jTextFieldAddLimit_per_amount;
    private javax.swing.JTextField jTextFieldAddLimit_per_day;
    private javax.swing.JTextField jTextFieldAddOverDraft;
    // End of variables declaration//GEN-END:variables
}
