/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

/**
 *
 * @author carlosforero
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopMenu = new javax.swing.JDesktopPane();
        jMenuMenu = new javax.swing.JMenuBar();
        jMenuMaestros = new javax.swing.JMenu();
        jMenuClients = new javax.swing.JMenuItem();
        jMenuAccounts = new javax.swing.JMenuItem();
        jMenuEmployees = new javax.swing.JMenuItem();
        jMenuTransacciones = new javax.swing.JMenu();
        jMenuWithDrawal = new javax.swing.JMenuItem();
        jMenuGeneral = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopMenuLayout = new javax.swing.GroupLayout(jDesktopMenu);
        jDesktopMenu.setLayout(jDesktopMenuLayout);
        jDesktopMenuLayout.setHorizontalGroup(
            jDesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1114, Short.MAX_VALUE)
        );
        jDesktopMenuLayout.setVerticalGroup(
            jDesktopMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );

        jMenuMaestros.setText("Maestros");

        jMenuClients.setText("Clientes");
        jMenuClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientsActionPerformed(evt);
            }
        });
        jMenuMaestros.add(jMenuClients);

        jMenuAccounts.setText("Cuentas");
        jMenuAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAccountsActionPerformed(evt);
            }
        });
        jMenuMaestros.add(jMenuAccounts);

        jMenuEmployees.setText("Empleados");
        jMenuEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmployeesActionPerformed(evt);
            }
        });
        jMenuMaestros.add(jMenuEmployees);

        jMenuMenu.add(jMenuMaestros);

        jMenuTransacciones.setText("Transacciones");

        jMenuWithDrawal.setText("Retiro y consignaciones");
        jMenuWithDrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuWithDrawalActionPerformed(evt);
            }
        });
        jMenuTransacciones.add(jMenuWithDrawal);

        jMenuMenu.add(jMenuTransacciones);

        jMenuGeneral.setText("General");

        jMenuAbout.setText("Acerca de");
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenuGeneral.add(jMenuAbout);

        jMenuMenu.add(jMenuGeneral);

        setJMenuBar(jMenuMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientsActionPerformed
        InternalClient clienteForm = new InternalClient();
        clienteForm.setVisible(true);
        clienteForm.setMaximizable(true);
        clienteForm.setResizable(true);
        clienteForm.setIconifiable(true);
        clienteForm.setClosable(true);
        jDesktopMenu.add(clienteForm);
        
    }//GEN-LAST:event_jMenuClientsActionPerformed

    private void jMenuAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAccountsActionPerformed
        InternalAccount clienteForm = new InternalAccount();
        clienteForm.setVisible(true);
        clienteForm.setMaximizable(true);
        clienteForm.setResizable(true);
        clienteForm.setIconifiable(true);
        clienteForm.setClosable(true);
        jDesktopMenu.add(clienteForm);
    }//GEN-LAST:event_jMenuAccountsActionPerformed

    private void jMenuWithDrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuWithDrawalActionPerformed
        InternalTransactions clienteForm = new InternalTransactions();
        clienteForm.setVisible(true);
        clienteForm.setMaximizable(true);
        clienteForm.setResizable(true);
        clienteForm.setIconifiable(true);
        clienteForm.setClosable(true);
        jDesktopMenu.add(clienteForm);
    }//GEN-LAST:event_jMenuWithDrawalActionPerformed

    private void jMenuEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmployeesActionPerformed
        InternalEmployee clienteForm = new InternalEmployee();
        clienteForm.setVisible(true);
        clienteForm.setMaximizable(true);
        clienteForm.setResizable(true);
        clienteForm.setIconifiable(true);
        clienteForm.setClosable(true);
        jDesktopMenu.add(clienteForm);
    }//GEN-LAST:event_jMenuEmployeesActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        InternalAbout clienteForm = new InternalAbout();
        clienteForm.setVisible(true);
        clienteForm.setMaximizable(true);
        clienteForm.setResizable(true);
        clienteForm.setIconifiable(true);
        clienteForm.setClosable(true);
        jDesktopMenu.add(clienteForm);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopMenu;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuItem jMenuAccounts;
    private javax.swing.JMenuItem jMenuClients;
    private javax.swing.JMenuItem jMenuEmployees;
    private javax.swing.JMenu jMenuGeneral;
    private javax.swing.JMenu jMenuMaestros;
    private javax.swing.JMenuBar jMenuMenu;
    private javax.swing.JMenu jMenuTransacciones;
    private javax.swing.JMenuItem jMenuWithDrawal;
    // End of variables declaration//GEN-END:variables
}
